#
#                           SIMPLY STAFF
#         Advanced chat protection, antiwdl, anti plugins viewer
#                            More soon...
#
#   This is the main configuration file for SimplyStaff (config.yml)
#
#          If you need help with the configuration or have any
#       Questions related to DragonSecurity, join us in our Discord.
#
#                 Discord: https://discord.gg/qkh857V2Nt
#                           Config: 1.2
#

#
# MESSAGE PLACEHOLDERS:
#
# » %player% - Name of the player
# » %staff% - Name of the staff
# » %command% - Name of the command (sudo only)
#

# Enable or disable alerts to staff members who have permission "ss.alert", example:
# SimplyStaff » Player has set his gamemode to creative
STAFF-ALERTS:
  enabled: true
  join-staff: "&b&lSimplyStaff &8» &a%player% &7joined the server!"

COMMANDS:

  # Gamemodes
  Gamemodes:

    error: "&b&lSimplyStaff &8» &cYou are already in this gamemode"

    survival:
      message: "&b&lSimplyStaff &8» &aYour gamemode now is survival"
      alert: "&b&lSimplyStaff &8» &a%player% &7has set his gamemode to &asurvival"

    creative:
      message: "&b&lSimplyStaff &8» &aYour gamemode now is creative"
      alert: "&b&lSimplyStaff &8» &a%player% &7has set his gamemode to &acreative"

    adventure:
      message: "&b&lSimplyStaff &8» &aYour gamemode now is adventure"
      alert: "&b&lSimplyStaff &8» &a%player% &7has set his gamemode to &aadventure"

    spectator:
      message: "&b&lSimplyStaff &8» &aYour gamemode now is spectator"
      alert: "&b&lSimplyStaff &8» &a%player% &7has set his gamemode to &aspectator"

  Basic:
    day: "&b&lSimplyStaff &8» &aTime set to day successfully in the world"
    night: "&b&lSimplyStaff &8» &aTime set to night successfully in the world"
    kill:
      message: "&b&lSimplyStaff &8» &aYou have successfully killed %player%"
      alert: "&b&lSimplyStaff &8» &a%staff% has killed %player%"
    godmode:
      setted: "&b&lSimplyStaff &8» &aYou have successfully setted godmode to %player%"
      removed: "&b&lSimplyStaff &8» &aYou have successfully removed godmode to %player%"
      alert-setted: "&b&lSimplyStaff &8» &7%staff% has &asetted &7godmode to &a%player%"
      alert-removed: "&b&lSimplyStaff &8» &7%staff% has &cremoved &7godmode to &a%player%"
    fly:
      enabled: "&b&lSimplyStaff &8» &aYou have successfully enabled fly to %player%"
      disabled: "&b&lSimplyStaff &8» &aYou have successfully disabled fly to %player%"
      alert-enabled: "&b&lSimplyStaff &8» &7%staff% has &aenabled &7fly to &a%player%"
      alert-disabled: "&b&lSimplyStaff &8» &7%staff% has &cdisabled &7fly to &a%player%"
    heal:
      message: "&b&lSimplyStaff &8» &aYou have successfully healed!"
      alert: "&b&lSimplyStaff &8» &7%staff% has healed &a%player%"
    clear:
      message: "&b&lSimplyStaff &8» &aYou have cleared the inventory of %player%"
      alert: "&b&lSimplyStaff &8» &7%staff% has cleared the inventory of &a%player%"
    teleport:
      message: "&b&lSimplyStaff &8» &aYou teleported to %player%"
      alert: "&b&lSimplyStaff &8» &7%staff% teleported to &a%player%"
    teleporthere:
      message: "&b&lSimplyStaff &8» &aYou teleported %player% to you"
      alert: "&b&lSimplyStaff &8» &7%staff% teleported &a%player% &7to him"
    teleportpos:
      message: "&b&lSimplyStaff &8» &aYou teleported to x: %x% y: %y% z: %z%"
      alert: "&b&lSimplyStaff &8» &a%staff% &7teleported to x: %x% y: %y% z: %z%"

  Advanced:
    sudo:
      message: "&b&lSimplyStaff &8» &aYou have successfully forced %player% to execute &c%command%"
      alert: "&b&lSimplyStaff &8» &a%staff% has forced %player% to execute &c%command%"

OTHER:
  config-reloaded: "&b&lSimplyStaff &8» &aConfig reloaded successfully!"
  server: "Minigame"

# Error
ERROR:
  only-player: "&b&lSimplyStaff &8» &cError: Only players can execute this command!"
  no-permission: "&b&lSimplyStaff &8» &cError: You don't have permission to do this"
  incorrect-syntax: "&b&lSimplyStaff &8» &cError: Incorrect syntax!"
  specify-world: "&b&lSimplyStaff &8» &cSpecify the world!"
  non-existent-world: "&b&lSimplyStaff &8» &cError: Non-existent world"
  specify-player: "&b&lSimplyStaff &8» &cSpecify the player!"
  non-existent-player: "&b&lSimplyStaff &8» &cError: Non-existent player"
  invalid-coordinates: "&b&lSimplyStaff &8» &cError: invalid coordinates!"