#
#                           DRAGON SECURITY
#         Advanced chat protection, antiwdl, anti plugins viewer
#                            More soon...
#
#   This is the main configuration file for DragonSecurity (config.yml)
#
#          If you need help with the configuration or have any
#       Questions related to DragonSecurity, join us in our Discord.
#
#                        Discord: (ComingSoon)
#                            Config: 1.0
#

#
# MESSAGE PLACHEHOLDERS:
#
# » %player% - Name of the player
#

# Gamemodes
Gamemodes:

  # Enable or disable alerts to staff who have permission "ss.alert", example:
  # SimplyStaff » Player has set his gamemode of creative
  staff-alerts: true

  error: "&b&lSimplyStaff &8» &cYou are already in this gamemode"

  survival:
    message: "&b&lSimplyStaff &8» &aYour gamemode now is survival"
    alert: "&b&lSimplyStaff &8» &7%player% has set his gamemode of &csurvival"

  creative:
    message: "&b&lSimplyStaff &8» &aYour gamemode now is creative"
    alert: "&b&lSimplyStaff &8» &7%player% has set his gamemode of &ccreative"

  adventure:
    message: "&b&lSimplyStaff &8» &aYour gamemode now is adventure"
    alert: "&b&lSimplyStaff &8» &7%player% has set his gamemode of &cadventure"

  spectator:
    message: "&b&lSimplyStaff &8» &aYour gamemode now is spectator"
    alert: "&b&lSimplyStaff &8» &7%player% has set his gamemode of &cspectator"

Help:
  - "&b&lSimplyStaff &7- by killernik\n"
  - "&7&oAlias: /simplestaff & /ss\n"
  - "\n"
  - "&8» &a/ss reload\n"
  - "&8» &a/gm(c|s|sp|a) [player]\n"

Other:
  config-reloaded: "&b&lSimplyStaff &8» &aConfig reloaded!"

# Error
Error:
  only-player: "SIMPLYSTAFF » Error, Only player can execute this command!"