name: SimplyStaff
version: '${version}'
main: it.killernik.simplystaff.SimplyStaff
commands:
  gmc:
    description: Gamemode creative
    usage: /gmc
  gma:
    description: Gamemode adventure
    usage: /gma
  gmsp:
    description: Gamemode spectator
    usage: /gmsp
  gms:
    description: Gamemode survival
    usage: /gms
  ss:
    description: Main Command
    usage: /ss