name: SimplyStaff
version: '1.4'
main: it.killernik.simplystaff.SimplyStaff
description: A simple and lightweight staff plugin
author: killernik
website: discord.com/invite/qHn2RTyTV7
commands:
  gmc:
    description: Gamemode creative
    usage: /gmc
  gma:
    description: Gamemode adventure
    usage: /gma
  gmsp:
    description: Gamemode spectator
    usage: /gmsp
  gms:
    description: Gamemode survival
    usage: /gms
  day:
    description: Day Command
    usage: /day
  night:
    description: Night Command
    usage: /night
  kill:
    description: Kill Command
    usage: /kill
  ss:
    description: Main Command
    usage: /ss
  godmode:
    description: Godmode Command
    usage: /godmode
    aliases:
      - god
  heal:
    description: Heal Command
    usage: /heal
  fly:
    description: Fly Command
    usage: /fly
  clear:
    description: Clear Command
    usage: /clear
  teleport:
    description: Teleport Command
    usage: /teleport
    aliases:
      - tp
  teleporthere:
    description: Teleporthere Command
    usage: /teleporthere
    aliases:
      - tph
  teleportpos:
    description: Teleportpos Command
    usage: /teleportpos
    aliases:
      - tppos
  serverinfo:
    description: Serverinfo Command
    usage: /serverinfo
    aliases:
      - si
  sudo:
    description: Sudo Command
    usage: /sudo
  freeze:
    description: Freeze Command
    usage: /freeze
