name: SimplyStaff
version: '${version}'
main: it.killernik.simplystaff.SimplyStaff
commands:
  gmc:
    description: Gamemode creative
    usage: /gmc
    aliases:
      - gamemode c
  gma:
    description: Gamemode adventure
    usage: /gma
    aliases:
      - gamemode a
  gmsp:
    description: Gamemode spectator
    usage: /gmsp
    aliases:
      - gamemode sp
  gms:
    description: Gamemode survival
    usage: /gms
    aliases:
      - gamemode s
  ss:
    description: Main Command
    usage: /ss
    aliases:
      - simplestaff