name: SimplyStaff
version: '${version}'
main: it.killernik.simplystaff.SimplyStaff
commands:
  gmc:
    description: Gamemode creative
    usage: /gmc
  gma:
    description: Gamemode adventure
    usage: /gma
  gmsp:
    description: Gamemode spectator
    usage: /gmsp
  gms:
    description: Gamemode survival
    usage: /gms
  day:
    description: Day Command
    usage: /day
  night:
    description: Night Command
    usage: /night
  kill:
    description: Kill Command
    usage: /kill
  ss:
    description: Main Command
    usage: /ss
  godmode:
    description: Godmode Command
    usage: /godmode
    aliases:
      - god
  heal:
    description: Heal Command
    usage: /heal
  fly:
    description: Fly Command
    usage: /fly
